In [194]:
import pandas as pd
from sklearn  import preprocessing
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score
from sklearn import linear_model
clf = linear_model.Lasso(alpha=0.1)
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler

In [129]:
data = pd.read_csv('Train_Data.csv')
test= pd.read_csv('Test_Data.csv')

In [130]:
data.tail()
test.head()


date    campaign    adgroup    ad  cost  impressions  clicks  \
0  01-03-2021  campaign 1  adgroup 1  ad 1  0.58          121      49   
1  01-03-2021  campaign 1  adgroup 3  ad 1  0.17           22      12   
2  01-03-2021  campaign 1  adgroup 4  ad 1  0.05            5       3   
3  01-03-2021  campaign 1  adgroup 2  ad 1  0.01            2       1   
4  01-03-2021  campaign 1  adgroup 2  ad 2  0.01            3       1   

   conversions  
0            1  
1            0  
2            0  
3            0  
4            0

In [131]:
data.dtypes

date            object
campaign        object
adgroup         object
ad              object
impressions      int64
clicks           int64
cost           float64
conversions      int64
revenue        float64
dtype: object

In [132]:
le = preprocessing.LabelEncoder()
s=le.fit_transform(data.campaign)

In [133]:
test['campaignenc']=le.fit_transform(test.campaign)

In [134]:
test['adgrpenc']=le.fit_transform(test.adgroup)

In [135]:
test['adenc']=le.fit_transform(test.ad)

In [136]:
test.head()

date    campaign    adgroup    ad  cost  impressions  clicks  \
0  01-03-2021  campaign 1  adgroup 1  ad 1  0.58          121      49   
1  01-03-2021  campaign 1  adgroup 3  ad 1  0.17           22      12   
2  01-03-2021  campaign 1  adgroup 4  ad 1  0.05            5       3   
3  01-03-2021  campaign 1  adgroup 2  ad 1  0.01            2       1   
4  01-03-2021  campaign 1  adgroup 2  ad 2  0.01            3       1   

   conversions  campaignenc  adgrpenc  adenc  
0            1            0         0      0  
1            0            0         2      0  
2            0            0         3      0  
3            0            0         1      0  
4            0            0         1      2

In [137]:
data['campaignenc']= s

In [138]:
data.head()

date    campaign    adgroup    ad  impressions  clicks  cost  \
0  01-08-2020  campaign 1  adgroup 1  ad 1           24       6  0.08   
1  01-08-2020  campaign 1  adgroup 2  ad 1            1       0  0.00   
2  01-08-2020  campaign 1  adgroup 3  ad 1           13       4  0.04   
3  01-08-2020  campaign 1  adgroup 4  ad 1            5       4  0.08   
4  01-08-2020  campaign 1  adgroup 1  ad 2          247     126  1.29   

   conversions  revenue  campaignenc  
0            0     0.00            0  
1            0     0.00            0  
2            0     0.00            0  
3            0     0.00            0  
4            4   925.71            0

In [139]:
v=le.fit_transform(data.adgroup)

In [140]:
data['adgrpenc']=v


In [141]:
u=le.fit_transform(data.ad)
data['adenc'] = u

In [142]:
data.head()

date    campaign    adgroup    ad  impressions  clicks  cost  \
0  01-08-2020  campaign 1  adgroup 1  ad 1           24       6  0.08   
1  01-08-2020  campaign 1  adgroup 2  ad 1            1       0  0.00   
2  01-08-2020  campaign 1  adgroup 3  ad 1           13       4  0.04   
3  01-08-2020  campaign 1  adgroup 4  ad 1            5       4  0.08   
4  01-08-2020  campaign 1  adgroup 1  ad 2          247     126  1.29   

   conversions  revenue  campaignenc  adgrpenc  adenc  
0            0     0.00            0         0      0  
1            0     0.00            0         1      0  
2            0     0.00            0         2      0  
3            0     0.00            0         3      0  
4            4   925.71            0         0     11

In [143]:
data.tail()

date    campaign    adgroup     ad  impressions  clicks  cost  \
4566  28-02-2021  campaign 1  adgroup 3  ad 55           19       6  0.07   
4567  28-02-2021  campaign 1  adgroup 4  ad 55            1       0  0.00   
4568  28-02-2021  campaign 1  adgroup 3  ad 56           16       8  0.12   
4569  28-02-2021  campaign 1  adgroup 1  ad 56           37      13  0.23   
4570  28-02-2021  campaign 1  adgroup 1  ad 55           19      10  0.14   

      conversions  revenue  campaignenc  adgrpenc  adenc  
4566            0      0.0            0         2     50  
4567            0      0.0            0         3     50  
4568            1     93.2            0         2     51  
4569            0      0.0            0         0     51  
4570            0      0.0            0         0     50

In [144]:
data['dateenc'] = le.fit_transform(data.date)

In [145]:
test['dateenc'] = le.fit_transform(test.date)

In [146]:
data.head()
data.shape
test.shape

(318, 12)

In [147]:
day = []
month =[]
year=[]
for i in range(4571):
    day.append(data['date'][i][:2])
    month.append(data['date'][i][3:5])
    year.append(data['date'][i][6:])
day
data['dayenc']=day
data['monthenc']=month
data['yearenc']=year
data.head()


date    campaign    adgroup    ad  impressions  clicks  cost  \
0  01-08-2020  campaign 1  adgroup 1  ad 1           24       6  0.08   
1  01-08-2020  campaign 1  adgroup 2  ad 1            1       0  0.00   
2  01-08-2020  campaign 1  adgroup 3  ad 1           13       4  0.04   
3  01-08-2020  campaign 1  adgroup 4  ad 1            5       4  0.08   
4  01-08-2020  campaign 1  adgroup 1  ad 2          247     126  1.29   

   conversions  revenue  campaignenc  adgrpenc  adenc  dateenc dayenc  \
0            0     0.00            0         0      0        2     01   
1            0     0.00            0         1      0        2     01   
2            0     0.00            0         2      0        2     01   
3            0     0.00            0         3      0        2     01   
4            4   925.71            0         0     11        2     01   

  monthenc yearenc  
0       08    2020  
1       08    2020  
2       08    2020  
3       08    2020  
4       08    2020

In [148]:
tday = []
tmonth =[]
tyear=[]
for i in range(318):
    tday.append(test['date'][i][:2])
    tmonth.append(test['date'][i][3:5])
    tyear.append(test['date'][i][6:])
day
test['dayenc']=tday
test['monthenc']=tmonth
test['yearenc']=tyear
test.head()


date    campaign    adgroup    ad  cost  impressions  clicks  \
0  01-03-2021  campaign 1  adgroup 1  ad 1  0.58          121      49   
1  01-03-2021  campaign 1  adgroup 3  ad 1  0.17           22      12   
2  01-03-2021  campaign 1  adgroup 4  ad 1  0.05            5       3   
3  01-03-2021  campaign 1  adgroup 2  ad 1  0.01            2       1   
4  01-03-2021  campaign 1  adgroup 2  ad 2  0.01            3       1   

   conversions  campaignenc  adgrpenc  adenc  dateenc dayenc monthenc yearenc  
0            1            0         0      0        0     01       03    2021  
1            0            0         2      0        0     01       03    2021  
2            0            0         3      0        0     01       03    2021  
3            0            0         1      0        0     01       03    2021  
4            0            0         1      2        0     01       03    2021

In [170]:
df = data.drop(['campaign','adgroup','ad','date'],axis=1)
dft = test.drop(['campaign','adgroup','ad','date'],axis=1)
df2 = data.drop(['campaign','adgroup','ad','date','dateenc'],axis=1)

In [150]:
dft.head()

cost  impressions  clicks  conversions  campaignenc  adgrpenc  adenc  \
0  0.58          121      49            1            0         0      0   
1  0.17           22      12            0            0         2      0   
2  0.05            5       3            0            0         3      0   
3  0.01            2       1            0            0         1      0   
4  0.01            3       1            0            0         1      2   

   dateenc dayenc monthenc yearenc  
0        0     01       03    2021  
1        0     01       03    2021  
2        0     01       03    2021  
3        0     01       03    2021  
4        0     01       03    2021

In [151]:

x

array([  2,   2,   2, ..., 190, 190, 190])

In [171]:
X_train=df.drop('revenue',axis=1)
X_train1=df2.drop('revenue',axis=1)

In [153]:
X_train.head()

impressions  clicks  cost  conversions  campaignenc  adgrpenc  adenc  \
0           24       6  0.08            0            0         0      0   
1            1       0  0.00            0            0         1      0   
2           13       4  0.04            0            0         2      0   
3            5       4  0.08            0            0         3      0   
4          247     126  1.29            4            0         0     11   

   dateenc dayenc monthenc yearenc  
0        2     01       08    2020  
1        2     01       08    2020  
2        2     01       08    2020  
3        2     01       08    2020  
4        2     01       08    2020

In [154]:
dft.head()

cost  impressions  clicks  conversions  campaignenc  adgrpenc  adenc  \
0  0.58          121      49            1            0         0      0   
1  0.17           22      12            0            0         2      0   
2  0.05            5       3            0            0         3      0   
3  0.01            2       1            0            0         1      0   
4  0.01            3       1            0            0         1      2   

   dateenc dayenc monthenc yearenc  
0        0     01       03    2021  
1        0     01       03    2021  
2        0     01       03    2021  
3        0     01       03    2021  
4        0     01       03    2021

In [155]:
y_train = df['revenue'] 

In [156]:
y_train.head()

0      0.00
1      0.00
2      0.00
3      0.00
4    925.71
Name: revenue, dtype: float64

In [157]:
lr = LinearRegression()

In [192]:
lr.fit(X_train, y_train)
lr.fit(X_train1, y_train)

LinearRegression()

In [172]:
lr.predict(X_train)
lr.score(X_train, y_train)

0.9402359994401038

In [175]:

print("traing score  ",accuracy_score(y_train,lr.predict(X_train)))
#print("testing score  ",accuracy_score(y_test,lr.predict(X_tests)))

ValueError: continuous is not supported

In [161]:
target = lr.predict(dft)

In [162]:
res = pd.DataFrame(target)

In [163]:
res.index= dft.index

In [165]:
res.columns = ["revenue"]
res.to_csv("prediction_results1.csv", index = False)

In [179]:
clf.fit(X_train,y_train)

Lasso(alpha=0.1)

In [193]:
lr.score(X_train1,y_train)

0.940235834471643

In [183]:
clf.predict(dft)

array([ 4.94908519e+01, -8.60900243e+01, -4.57378566e+01, -3.89074071e+01,
       -3.71629069e+01, -4.00049211e+01, -2.27459311e+02, -2.04055531e+01,
       -7.15736672e+01, -6.29946455e+01,  3.80654174e+02, -1.06401288e+02,
       -6.05068127e+01,  4.62297148e+01, -4.95892002e+01,  1.50180866e+02,
       -8.21956219e+01, -4.63765092e+01, -1.03619918e+02,  9.21616696e+01,
       -2.02066381e+01, -1.85126879e+02, -4.51824465e+01,  1.99091812e+02,
       -2.90498982e+01, -4.34379464e+01,  5.00827148e+02, -1.94492197e+02,
       -5.07050540e+01, -3.06475392e+01,  5.41529156e+02, -4.95517897e+01,
        8.69418430e+02,  3.11129688e+02,  1.42445452e+02, -4.13317297e+01,
       -4.33699414e+01, -5.28810582e+01, -2.51547441e+01, -6.55076199e+01,
       -7.58704741e+01, -5.56764216e+01, -3.29487052e+01, -1.09398792e+02,
       -1.07919054e+02, -3.84376595e+01, -4.34539888e+01, -4.52106535e+01,
       -1.03511622e+02, -4.28819280e+01, -3.56560249e+01, -5.89517156e+01,
       -1.31876387e+02,  

In [182]:
target

array([ 4.88822346e+01, -8.62619158e+01, -4.57699228e+01, -3.91313886e+01,
       -3.73808188e+01, -4.00261411e+01, -2.28431629e+02, -2.06275401e+01,
       -7.20660283e+01, -6.30152736e+01,  3.79642850e+02, -1.06554775e+02,
       -6.06409352e+01,  4.57945851e+01, -4.97761142e+01,  1.49673244e+02,
       -8.23362453e+01, -4.68909131e+01, -1.03990531e+02,  9.54882885e+01,
       -1.67341710e+01, -1.82214003e+02, -4.19051599e+01,  2.01621650e+02,
       -2.55607855e+01, -4.01545901e+01,  5.03319840e+02, -1.91559461e+02,
       -4.72254369e+01, -2.73555381e+01,  5.44873240e+02, -4.61755795e+01,
        8.72513641e+02,  3.14111570e+02,  1.45818313e+02, -3.80231404e+01,
       -4.03485614e+01, -4.97635474e+01, -1.81735769e+01, -5.86312509e+01,
       -6.92126273e+01, -4.90834904e+01, -2.61506479e+01, -1.02607008e+02,
       -1.01383906e+02, -3.14402663e+01, -3.65665033e+01, -3.83087468e+01,
       -9.66360926e+01, -3.62043660e+01, -2.88318266e+01, -5.20467340e+01,
       -1.25024004e+02,  

In [185]:
np = MLPRegressor()

In [186]:
np.fit(X_train,y_train)

C:\Users\User\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPRegressor()

In [188]:
target1= np.predict(dft)

In [189]:
res = pd.DataFrame(target1)

In [190]:
res.index= dft.index

In [191]:
res.columns = ["revenue"]
res.to_csv("prediction_results2.csv", index = False)

In [201]:
scaler=StandardScaler()
X_trains=pd.DataFrame(scaler.fit_transform(X_train))
X_tests=scaler.transform(dft)
X_trains

0         1         2         3    4         5         6   \
0    -0.346072 -0.372834 -0.189472 -0.256367  0.0 -1.328065 -1.291476   
1    -0.462041 -0.432742 -0.195043 -0.256367  0.0 -0.414508 -1.291476   
2    -0.401535 -0.392804 -0.192258 -0.256367  0.0  0.499049 -1.291476   
3    -0.441873 -0.392804 -0.189472 -0.256367  0.0  1.412606 -1.291476   
4     0.778328  0.825321 -0.105211  0.509425  0.0 -1.328065 -0.814974   
...        ...       ...       ...       ...  ...       ...       ...   
4566 -0.371283 -0.372834 -0.190169 -0.256367  0.0  0.499049  0.874441   
4567 -0.462041 -0.432742 -0.195043 -0.256367  0.0  1.412606  0.874441   
4568 -0.386409 -0.352865 -0.186687 -0.064919  0.0  0.499049  0.917759   
4569 -0.280524 -0.302942 -0.179027 -0.256367  0.0 -1.328065  0.917759   
4570 -0.371283 -0.332896 -0.185294 -0.256367  0.0 -1.328065  0.874441   

            7         8         9         10  
0    -1.674046 -1.653649  0.103533 -0.663088  
1    -1.674046 -1.653649  0.103533 -0.663088  
2    -1.674046 -1.653649  0.103533 -0.663088  
3    -1.674046 -1.653649  0.103533 -0.663088  
4    -1.674046 -1.653649  0.103533 -0.663088  
...        ...       ...       ...       ...  
4566  1.391521  1.418954 -1.315509  1.508097  
4567  1.391521  1.418954 -1.315509  1.508097  
4568  1.391521  1.418954 -1.315509  1.508097  
4569  1.391521  1.418954 -1.315509  1.508097  
4570  1.391521  1.418954 -1.315509  1.508097  

[4571 rows x 11 columns]

In [204]:
lr.fit(X_trains, y_train)
lr.predict(dft)




array([-128273.45898921, -150604.13755614, -153873.72451847,
       -154395.32311821, -154151.11800167, -154020.55209036,
        -97391.2707452 , -153231.16866523, -120901.97817046,
       -153914.23093342,  -88597.18467501, -150911.13925849,
       -151825.02707411, -123462.24323689, -154359.08358482,
       -132911.57582342, -149899.58385979, -113986.76342053,
       -150369.31708006, -148954.32635824, -153733.17315961,
       -131702.66048736, -154273.88980031,  -94143.10243218,
       -154548.31489445, -154029.68468377,  -87992.11127195,
       -115047.74343046, -153515.51614099, -154298.16391549,
       -145634.85919919, -152352.7898782 , -119960.92003044,
       -130626.99720951, -149144.68745576, -153577.99332756,
       -116894.26910215, -148492.44748326, -154270.49498417,
       -154168.48775862, -152449.88601498, -145616.32587996,
       -154570.64902721, -145804.01824708, -140531.67376375,
       -154704.91982875, -153402.79605102, -154333.81796329,
       -151355.84619609,